services:
  db:
    image: mysql:8.0
    container_name: prisma_db_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pr!5m@
      MYSQL_DATABASE: prisma_db
      MYSQL_USER: prisma_user
      MYSQL_PASSWORD: Pr!5m@
    ports:
      - "3307:3306" # No PC usamos 3307 para não dar conflito se você já tiver MySQL instalado
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: prisma_app
    ports:
      - "7777:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
