name: Deploy Prisma via Tailscale

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar ao Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Executar Script de Update no Servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}      # Seu IP 100.x.y.z salvo nos Secrets
          username: ${{ secrets.SSH_USER }}    # Seu usuário 'rbp' salvo nos Secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Sua chave SSH salva nos Secrets
          port: 22
          script: |
            # Executa o script usando o caminho absoluto que você confirmou
            /bin/bash /var/www/html/Prisma/scripts/update.sh
